# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*-pages/
      - deploy_product:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
      
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "book.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -g gitbook-cli

      - run: gitbook install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "book.json" }}
        
      - run: gitbook build

      - persist_to_workspace:
          root: _book
          paths:
            - \*

  deploy_product:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: _book
      - run: |
          cd _book
          git config --global user.name 'wangyf'
          git config --global user.email 'zgtjwyftc@gmail.com'
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "git@github.com:MasterStudio/MasterWechatApp.git" master:gh-pages
          git config --global user.name 'evanwang'
          git config --global user.email 'evan.wang.master@gmail.com'
          ssh -o "StrictHostKeyChecking no" git@git.coding.net
          git push --force "git@git.coding.net:MasterStudio/MasterWechatApp.git" master:coding-pages